### ISSUE TITLE
一但使用pwm的模块就网络中断。。。

### ISSUE THREAD

**Issue by lsyaizyl** [MrYsLab/s3onegpio#21] opened 2020-05-02 17:09 UTC

**Comment by lsyaizyl** [comment] 2020-05-02 19:18
具体如何解决，大神？

**Comment by lsyaizyl** [comment] 2020-05-02 19:18
我是使用scratch离线版的

**Comment by MrYsLab** [comment] 2020-05-02 19:27
I don't know if you mean the offline version provided by the Scratch team or my version. You must use my version. You can [find instructions here.](https://mryslab.github.io/s3-extend/#s3-local/)
If you are using my version, what browser are you using (Chrome, Firefox, etc)?

**Comment by lsyaizyl** [comment] 2020-05-02 19:28
我使用在您这里下载的版本，Chrome

**Comment by MrYsLab** [comment] 2020-05-02 19:29
Ok. You will need to follow the troubleshooting instructions as mentioned in issue #22.

**Comment by lsyaizyl** [comment] 2020-05-02 19:36
pi@raspberrypi:~ $ s3r
Only run this script on a Raspberry Pi!
backplane started
Websocket Gateway started
RPi Gateway started 
To exit this program, press Control-c
RPi Gateway exited.
pi@raspberrypi:~ $

**Comment by lsyaizyl** [comment] 2020-05-02 19:36
![ba9c1641ccdef1f2607eec5f98149dd](https://user-images.githubusercontent.com/48210229/80882404-4c18fd80-8cef-11ea-8489-ceecf9079ef6.png)

**Comment by lsyaizyl** [comment] 2020-05-02 19:38
![a43df33d7364e83b86b8961ca397b06](https://user-images.githubusercontent.com/48210229/80883179-84204080-8cef-11ea-861c-7686e69889d4.png)

**Comment by lsyaizyl** [comment] 2020-05-02 19:38
![a43df33d7364e83b86b8961ca397b06](https://user-images.githubusercontent.com/48210229/80883316-8da9a880-8cef-11ea-9665-b3faa912e710.png)

**Comment by MrYsLab** [comment] 2020-05-02 19:40
Now when you run s3onegpio and try to run PWM, does it crash? If so, is there any exception output in any of the screens?

**Comment by lsyaizyl** [comment] 2020-05-02 19:44
![image](https://user-images.githubusercontent.com/48210229/80886238-5b4c7b00-8cf0-11ea-8f3d-e300cfadbe76.png)

**Comment by lsyaizyl** [comment] 2020-05-02 19:44
不起作用了

**Comment by lsyaizyl** [comment] 2020-05-02 19:46
![image](https://user-images.githubusercontent.com/48210229/80887298-a5cdf780-8cf0-11ea-82ef-fc14de1ac9bb.png)

**Comment by lsyaizyl** [comment] 2020-05-02 19:46
已杀死

**Comment by lsyaizyl** [comment] 2020-05-02 19:48
![fe96fec42a56687461823e30507ce58](https://user-images.githubusercontent.com/48210229/80888220-e6c60c00-8cf0-11ea-9fdc-bdc936cf6ecb.png)

**Comment by MrYsLab** [comment] 2020-05-02 19:59
What pin number are you using in the Scratch block and what is percentage value you are using?

**Comment by lsyaizyl** [comment] 2020-05-02 20:08
无论是多少都会出现这个问题。。。

**Comment by lsyaizyl** [comment] 2020-05-02 20:08
只有使用pwm那个模块就会出现

**Comment by MrYsLab** [comment] 2020-05-02 20:08
What pin number are you using?

**Comment by MrYsLab** [comment] 2020-05-02 20:22
I don't know what you mean by 只有使用pwm那个模块就会出现. Could you please explain.

**Comment by MrYsLab** [comment] 2020-05-02 21:44
Ok I am able to reproduce what you are seeing. I believe that problem is in the s3onegpio code and not s3-extend. I am debugging and will get back to you as soon as I can isolate the bug.

**Comment by MrYsLab** [comment] 2020-05-02 22:03
Fixed with version 1.9. Download the browser files again and it should work. If you are still having issues, leave a comment here and I will reopen the issue.
The problem was that I had a maximum of 1024 for the PWM value which broke the calculations. It should have been 255.

**Closed by MrYsLab** 2020-05-02 22:03 UTC

**Comment by lsyaizyl** [comment] 2020-05-03 02:01
非常感谢，我昨晚已经睡觉了，抱歉。没有回复到您

**Comment by lsyaizyl** [comment] 2020-05-03 02:08
![image](https://user-images.githubusercontent.com/48210229/80896915-f875d680-8d25-11ea-9e89-372c167406b1.png)

**Comment by MrYsLab** [comment] 2020-05-03 12:44
It should work now with version 1.9 both off-line and online. Just download the files again to use it off line and it should work.

**Comment by lsyaizyl** [comment] 2020-05-07 17:35
大神，请问这个拓展能不能弄到scratch desktop上？？？

**Comment by lsyaizyl** [comment] 2020-05-07 17:35
一定要使用浏览器吗？

**Comment by MrYsLab** [comment] 2020-05-07 18:08
I am not sure if I understand your questions.
If you mean can you use my extensions with the Scratch Desktop that the Scratch team provides, then the answer is no. 

I don't know what you mean by "Are you sure you want to use a browser?". A browser must be used, but if you do not wish to go over the internet, you can [run things locally as explained here.](https://mryslab.github.io/s3-extend/#s3-local/)

I will not be providing a Windows .exe or any other OS executable file,  if that is what you mean.

**Comment by lsyaizyl** [comment] 2020-05-12 05:44
好的，谢谢大神，加油。
